#!/bin/bash
# P2 move

trap "/usr/bin/killall -q -u $USER ./ShutTheBox 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stderr=/dev/null ./ShutTheBox --two --move 123 3 3 < /dev/null
