#!/bin/bash
# P1 Mid-game move

trap "/usr/bin/killall -q -u $USER ./ShutTheBox 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stderr=/dev/null ./ShutTheBox --one --move 146789 9 < /dev/null
