#!/bin/bash
# P2 nonterminal but guaranteed win

trap "/usr/bin/killall -q -u $USER ./ShutTheBox 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stderr=/dev/null ./ShutTheBox --two --expect 12345689 41 < /dev/null
